### ISSUE TITLE
How to make it default check-in and check-out date blank

### ISSUE THREAD

**Issue by Janie-w3** [PredixDev/predix-seed#119]
I'm using [px-rangepicker](https://www.predix-ui.com/#/components/px-rangepicker/) and I want to set it default check-in and check-out dates blank but could not find a way to do that. Both check-in and check-out dates are getting the current date. I lost a day to find out the way to make it blank.

My custom element looks like this:

`<date-fields
            id="field"
            from-moment="{{fromMoment}}"
            to-moment="{{toMoment}}"
            time-zone="{{timeZone}}"
            date-format="{{dateFormat}}"
            time-format="{{timeFormat}}"
            hide-time="{{hideTime}}"
            block-future-dates="{{blockFutureDates}}"
            block-past-dates="{{blockPastDates}}"
            is-valid="{{isValid}}"
            show-time-zone="[[showTimeZone]]"
            prevent-notification-on-change
            resources="[[resources]]"
            language="[[language]]"
            formats="[[formats]]">
</date-fields>`

Could you please give me a suggestion to make it easy?

**Comment by gstroup** [comment]
This is an issue with the px-rangepicker component.  You can preset date & time to any date you like, but there's no way to make it blank.  I think there is already an issue raised in the px-rangepicker repo:
https://github.com/PredixDev/px-rangepicker/issues/32
You can comment on that one, or open a new issue if you think your issue is different.
